// Generated by gencpp from file learning_tf2/evaluateSLAMEvoResponse.msg
// DO NOT EDIT!


#ifndef LEARNING_TF2_MESSAGE_EVALUATESLAMEVORESPONSE_H
#define LEARNING_TF2_MESSAGE_EVALUATESLAMEVORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_tf2
{
template <class ContainerAllocator>
struct evaluateSLAMEvoResponse_
{
  typedef evaluateSLAMEvoResponse_<ContainerAllocator> Type;

  evaluateSLAMEvoResponse_()
    : rmse(0.0)  {
    }
  evaluateSLAMEvoResponse_(const ContainerAllocator& _alloc)
    : rmse(0.0)  {
  (void)_alloc;
    }



   typedef float _rmse_type;
  _rmse_type rmse;





  typedef boost::shared_ptr< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct evaluateSLAMEvoResponse_

typedef ::learning_tf2::evaluateSLAMEvoResponse_<std::allocator<void> > evaluateSLAMEvoResponse;

typedef boost::shared_ptr< ::learning_tf2::evaluateSLAMEvoResponse > evaluateSLAMEvoResponsePtr;
typedef boost::shared_ptr< ::learning_tf2::evaluateSLAMEvoResponse const> evaluateSLAMEvoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator1> & lhs, const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.rmse == rhs.rmse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator1> & lhs, const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_tf2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64ede1f40ef1c350e70bba074ccc7da2";
  }

  static const char* value(const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64ede1f40ef1c350ULL;
  static const uint64_t static_value2 = 0xe70bba074ccc7da2ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_tf2/evaluateSLAMEvoResponse";
  }

  static const char* value(const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 rmse\n"
"\n"
;
  }

  static const char* value(const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rmse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct evaluateSLAMEvoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_tf2::evaluateSLAMEvoResponse_<ContainerAllocator>& v)
  {
    s << indent << "rmse: ";
    Printer<float>::stream(s, indent + "  ", v.rmse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_TF2_MESSAGE_EVALUATESLAMEVORESPONSE_H
