// Generated by gencpp from file learning_tf2/evaluateSLAMEvo.msg
// DO NOT EDIT!


#ifndef LEARNING_TF2_MESSAGE_EVALUATESLAMEVO_H
#define LEARNING_TF2_MESSAGE_EVALUATESLAMEVO_H

#include <ros/service_traits.h>


#include <learning_tf2/evaluateSLAMEvoRequest.h>
#include <learning_tf2/evaluateSLAMEvoResponse.h>


namespace learning_tf2
{

struct evaluateSLAMEvo
{

typedef evaluateSLAMEvoRequest Request;
typedef evaluateSLAMEvoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct evaluateSLAMEvo
} // namespace learning_tf2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_tf2::evaluateSLAMEvo > {
  static const char* value()
  {
    return "35874a05cfbf0d3305ff4de33999af1f";
  }

  static const char* value(const ::learning_tf2::evaluateSLAMEvo&) { return value(); }
};

template<>
struct DataType< ::learning_tf2::evaluateSLAMEvo > {
  static const char* value()
  {
    return "learning_tf2/evaluateSLAMEvo";
  }

  static const char* value(const ::learning_tf2::evaluateSLAMEvo&) { return value(); }
};


// service_traits::MD5Sum< ::learning_tf2::evaluateSLAMEvoRequest> should match
// service_traits::MD5Sum< ::learning_tf2::evaluateSLAMEvo >
template<>
struct MD5Sum< ::learning_tf2::evaluateSLAMEvoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_tf2::evaluateSLAMEvo >::value();
  }
  static const char* value(const ::learning_tf2::evaluateSLAMEvoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_tf2::evaluateSLAMEvoRequest> should match
// service_traits::DataType< ::learning_tf2::evaluateSLAMEvo >
template<>
struct DataType< ::learning_tf2::evaluateSLAMEvoRequest>
{
  static const char* value()
  {
    return DataType< ::learning_tf2::evaluateSLAMEvo >::value();
  }
  static const char* value(const ::learning_tf2::evaluateSLAMEvoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_tf2::evaluateSLAMEvoResponse> should match
// service_traits::MD5Sum< ::learning_tf2::evaluateSLAMEvo >
template<>
struct MD5Sum< ::learning_tf2::evaluateSLAMEvoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_tf2::evaluateSLAMEvo >::value();
  }
  static const char* value(const ::learning_tf2::evaluateSLAMEvoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_tf2::evaluateSLAMEvoResponse> should match
// service_traits::DataType< ::learning_tf2::evaluateSLAMEvo >
template<>
struct DataType< ::learning_tf2::evaluateSLAMEvoResponse>
{
  static const char* value()
  {
    return DataType< ::learning_tf2::evaluateSLAMEvo >::value();
  }
  static const char* value(const ::learning_tf2::evaluateSLAMEvoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_TF2_MESSAGE_EVALUATESLAMEVO_H
