// Generated by gencpp from file learning_tf2/evaluateSLAMEvoRequest.msg
// DO NOT EDIT!


#ifndef LEARNING_TF2_MESSAGE_EVALUATESLAMEVOREQUEST_H
#define LEARNING_TF2_MESSAGE_EVALUATESLAMEVOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_tf2
{
template <class ContainerAllocator>
struct evaluateSLAMEvoRequest_
{
  typedef evaluateSLAMEvoRequest_<ContainerAllocator> Type;

  evaluateSLAMEvoRequest_()
    : cmd()  {
    }
  evaluateSLAMEvoRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct evaluateSLAMEvoRequest_

typedef ::learning_tf2::evaluateSLAMEvoRequest_<std::allocator<void> > evaluateSLAMEvoRequest;

typedef boost::shared_ptr< ::learning_tf2::evaluateSLAMEvoRequest > evaluateSLAMEvoRequestPtr;
typedef boost::shared_ptr< ::learning_tf2::evaluateSLAMEvoRequest const> evaluateSLAMEvoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator1> & lhs, const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator1> & lhs, const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_tf2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43a54fa49066cddcf148717d9d4a6353";
  }

  static const char* value(const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43a54fa49066cddcULL;
  static const uint64_t static_value2 = 0xf148717d9d4a6353ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_tf2/evaluateSLAMEvoRequest";
  }

  static const char* value(const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cmd\n"
;
  }

  static const char* value(const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct evaluateSLAMEvoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_tf2::evaluateSLAMEvoRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_TF2_MESSAGE_EVALUATESLAMEVOREQUEST_H
